name: build and publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '15 0 * * *'

env:
  ECR_REPO: public.ecr.aws/l5k6t5t7/base-images
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  node:
    env:
      IMAGE_NAME: node
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ lts ]
    name: node
    steps:
      - uses: actions/checkout@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Install dependencies
        uses: ./.github/actions/install-dep
      - name: ECR public login
        run: /usr/local/bin/aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
      - name: Build and Publish
        if: "!contains(github.event.head_commit.message, '[force build]')"
        with:
          docker_build_args: NODE_MAJOR_VERSION=${{ matrix.node-version }}
        uses: ./.github/actions/build-and-publish
      - name: Build and Publish (force)
        if: "contains(github.event.head_commit.message, '[force build]')"
        with:
          docker_build_args: NODE_MAJOR_VERSION=${{ matrix.node-version }}
        uses: ./.github/actions/build-and-publish-force